name: Windows
on:
  # Trigger the workflow on push,
  # but only for the master branch
  push:
    branches: 
      - master
jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Prepare
        run: |
          git submodule update --init
          md build32 
          cd build32
          cmake -Werror=dev -G "Visual Studio 16 2019" ..
          cd ..
          md build64 
          cd build64
          cmake -Werror=dev -G "Visual Studio 16 2019" -A x64 ..
          cd ..
      - name: Build Bam
        run: |
          md bam
          git clone https://github.com/matricks/bam.git bam
          cd bam
          .\make_win64_msvc.bat
      - name: Build win with Bam in Release mode
        run: |
          .\bam\bam conf=release content all
      - name: Build win32 with cmake in Release mode
        run: |
          cmake --build build32 --config Release --target everything
      - name: Build win64 with cmake
        run: |
          cmake --build build64 --config Release --target everything
      - name: Test win32
        run: |
          cd build32
          Release\teeworlds_srv shutdown
          cd ..
      - name: Test win64
        run: |
          cd build64
          Release\teeworlds_srv shutdown
          cd ..
